// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "devices/threads/threads_conf.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
void ui_event_ToOpenCVButton(lv_event_t * e);
lv_obj_t * ui_ToOpenCVButton;
lv_obj_t * ui_OpenCVLabel;
void ui_event_ToSetButton(lv_event_t * e);
lv_obj_t * ui_ToSetButton;
lv_obj_t * ui_SetLabel;
void ui_event_ToMessageButton(lv_event_t * e);
lv_obj_t * ui_ToMessageButton;
lv_obj_t * ui_MessageLabel;
void ui_event_ToPowerButton(lv_event_t * e);
lv_obj_t * ui_ToPowerButton;
lv_obj_t * ui_PowerLabel;
lv_obj_t * ui_PowerPanel;
void ui_event_ShutdownButton(lv_event_t * e);
lv_obj_t * ui_ShutdownButton;
lv_obj_t * ui_ShutdownLabel;
void ui_event_RebootButton(lv_event_t * e);
lv_obj_t * ui_RebootButton;
lv_obj_t * ui_RebootLabel;
void ui_event_PowerCancelButton(lv_event_t * e);
lv_obj_t * ui_PowerCancelButton;
lv_obj_t * ui_PowerCancelLabel;
lv_obj_t * ui_PowerAskLabel;
lv_obj_t * ui_TimePanel;
lv_obj_t * ui_Time1Label;
lv_obj_t * ui_Time2Label;
lv_obj_t * ui_UbuntuImage;
// CUSTOM VARIABLES

// SCREEN: ui_OpenCV
void ui_OpenCV_screen_init(void);
lv_obj_t * ui_OpenCV;
void ui_event_OpenCVToMainButton(lv_event_t * e);
lv_obj_t * ui_OpenCVToMainButton;
lv_obj_t * ui_OpenCVDemoLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Set
void ui_Set_screen_init(void);
void ui_event_Set(lv_event_t * e);
lv_obj_t * ui_Set;
void ui_event_SetToMainButton(lv_event_t * e);
lv_obj_t * ui_SetToMainButton;
lv_obj_t * ui_WiFiScanRoller;
lv_obj_t * ui_IPAddrLabel;
void ui_event_WiFiFreshButton(lv_event_t * e);
lv_obj_t * ui_WiFiFreshButton;
lv_obj_t * ui_WiFiFreshLabel;
void ui_event_WiFiConnectButton(lv_event_t * e);
lv_obj_t * ui_WiFiConnectButton;
lv_obj_t * ui_WiFiConnectLabel;
void ui_event_WiFiKeyboard(lv_event_t * e);
lv_obj_t * ui_WiFiKeyboard;
lv_obj_t * ui_WiFiEnterPassPanel;
lv_obj_t * ui_WiFiPassTextArea;
lv_obj_t * ui_WiFiSSIDLabel;
lv_obj_t * ui_WiFiConnectWaitSpinner;
// CUSTOM VARIABLES

// SCREEN: ui_Message
void ui_Message_screen_init(void);
lv_obj_t * ui_Message;
void ui_event_MessageToMainButton(lv_event_t * e);
lv_obj_t * ui_MessageToMainButton;
lv_obj_t * ui_BatteryLabel;
// CUSTOM VARIABLES


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ToOpenCVButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_OpenCV, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_OpenCV_screen_init);
        _ui_screen_delete(&ui_Main);
        
        // Creat OpenCV thread
        cv_create_thread();
    }
}

void ui_event_OpenCVToMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_OpenCV);
        
        // Terminate OpenCV thread
        cv_destroy_thread();
    }
}

void ui_event_ToSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Set_screen_init);
        _ui_screen_delete(&ui_Main);

        // Create WiFi thread
        wifi_create_thread();
    }
}

void ui_event_SetToMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Set);

        // Terminate WiFi thread
        wifi_destroy_thread();
    }
}

void ui_event_WiFiFreshButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Refresh WiFi list
        wifi_isflush();
    }
}

void ui_event_WiFiConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WiFiEnterPassPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WiFiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);

        // Display the Wi-Fi name to the password input page.
        char ssid_buf[256];
        lv_roller_get_selected_str(ui_WiFiScanRoller, ssid_buf, sizeof(ssid_buf));
        lv_label_set_text_fmt(ui_WiFiSSIDLabel, "%s", ssid_buf);
    }
}

void ui_event_WiFiKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_WiFiEnterPassPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WiFiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WiFiConnectWaitSpinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        
        // Get the Wi-Fi name and password
        char ssid_buf[256];
        const char *pass_buf;
        lv_roller_get_selected_str(ui_WiFiScanRoller, ssid_buf, sizeof(ssid_buf));
        pass_buf = lv_textarea_get_text(ui_WiFiPassTextArea);
        wifi_get_ssid(ssid_buf);
        wifi_get_pass(pass_buf);
        wifi_isconnect();
    }
}

void ui_event_Set(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_WiFiEnterPassPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WiFiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ToMessageButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Message, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Message_screen_init);
        _ui_screen_delete(&ui_Main);

        // Create information thread
        message_create_thread();
    }
}

void ui_event_MessageToMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Message);

        // Terminate information thread
        message_destroy_thread();
    }
}

void ui_event_ToPowerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PowerPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ShutdownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {

        // Power off
        power_shutdown();
    }
}

void ui_event_RebootButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {

        // Power reboot
        power_reboot();
    }
}

void ui_event_PowerCancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PowerPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_OpenCV_screen_init();
    ui_Set_screen_init();
    ui_Message_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}



