// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
void ui_event_ToOpenCVButton(lv_event_t * e);
extern lv_obj_t * ui_ToOpenCVButton;
extern lv_obj_t * ui_OpenCVLabel;
void ui_event_ToSetButton(lv_event_t * e);
extern lv_obj_t * ui_ToSetButton;
extern lv_obj_t * ui_SetLabel;
void ui_event_ToMessageButton(lv_event_t * e);
extern lv_obj_t * ui_ToMessageButton;
extern lv_obj_t * ui_MessageLabel;
void ui_event_ToPowerButton(lv_event_t * e);
extern lv_obj_t * ui_ToPowerButton;
extern lv_obj_t * ui_PowerLabel;
extern lv_obj_t * ui_PowerPanel;
void ui_event_ShutdownButton(lv_event_t * e);
extern lv_obj_t * ui_ShutdownButton;
extern lv_obj_t * ui_ShutdownLabel;
void ui_event_RebootButton(lv_event_t * e);
extern lv_obj_t * ui_RebootButton;
extern lv_obj_t * ui_RebootLabel;
void ui_event_PowerCancelButton(lv_event_t * e);
extern lv_obj_t * ui_PowerCancelButton;
extern lv_obj_t * ui_PowerCancelLabel;
extern lv_obj_t * ui_PowerAskLabel;
extern lv_obj_t * ui_TimePanel;
extern lv_obj_t * ui_Time1Label;
extern lv_obj_t * ui_Time2Label;
extern lv_obj_t * ui_UbuntuImage;
// CUSTOM VARIABLES

// SCREEN: ui_OpenCV
void ui_OpenCV_screen_init(void);
extern lv_obj_t * ui_OpenCV;
void ui_event_OpenCVToMainButton(lv_event_t * e);
extern lv_obj_t * ui_OpenCVToMainButton;
extern lv_obj_t * ui_OpenCVDemoLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Set
void ui_Set_screen_init(void);
void ui_event_Set(lv_event_t * e);
extern lv_obj_t * ui_Set;
void ui_event_SetToMainButton(lv_event_t * e);
extern lv_obj_t * ui_SetToMainButton;
extern lv_obj_t * ui_WiFiScanRoller;
extern lv_obj_t * ui_IPAddrLabel;
void ui_event_WiFiFreshButton(lv_event_t * e);
extern lv_obj_t * ui_WiFiFreshButton;
extern lv_obj_t * ui_WiFiFreshLabel;
void ui_event_WiFiConnectButton(lv_event_t * e);
extern lv_obj_t * ui_WiFiConnectButton;
extern lv_obj_t * ui_WiFiConnectLabel;
void ui_event_WiFiKeyboard(lv_event_t * e);
extern lv_obj_t * ui_WiFiKeyboard;
extern lv_obj_t * ui_WiFiEnterPassPanel;
extern lv_obj_t * ui_WiFiPassTextArea;
extern lv_obj_t * ui_WiFiSSIDLabel;
extern lv_obj_t * ui_WiFiConnectWaitSpinner;
// CUSTOM VARIABLES

// SCREEN: ui_Message
void ui_Message_screen_init(void);
extern lv_obj_t * ui_Message;
void ui_event_MessageToMainButton(lv_event_t * e);
extern lv_obj_t * ui_MessageToMainButton;
extern lv_obj_t * ui_BatteryLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_opencv_realease_png);    // assets/OpenCV_Realease.png
LV_IMG_DECLARE(ui_img_opencv_press_png);    // assets/OpenCV_Press.png
LV_IMG_DECLARE(ui_img_set_realease_png);    // assets/Set_Realease.png
LV_IMG_DECLARE(ui_img_set_press_png);    // assets/Set_Press.png
LV_IMG_DECLARE(ui_img_message_realease_png);    // assets/Message_Realease.png
LV_IMG_DECLARE(ui_img_message_press_png);    // assets/Message_Press.png
LV_IMG_DECLARE(ui_img_power_release_png);    // assets/Power_Release.png
LV_IMG_DECLARE(ui_img_power_press_png);    // assets/Power_Press.png
LV_IMG_DECLARE(ui_img_ubuntu_logo_png);    // assets/Ubuntu_Logo.png
LV_IMG_DECLARE(ui_img_back_realease__png);    // assets/Back_Realease .png
LV_IMG_DECLARE(ui_img_back_press_png);    // assets/Back_Press.png

// FONTS
LV_FONT_DECLARE(ui_font_AlimamaShuHeiTi_16);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
